spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC  # DB Timezone configure
        format_sql: true  # SQL pretty print
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            redirect-uri: https://catvillage.shop/login/oauth2/code/kakao
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
cloud:
  aws:
    s3:
      bucket: image.catvillage.shop
      dir: catvillage/images/
    region:
      static: ap-northeast-2
    stack:
      auto: false